### ISSUE TITLE
Plugin cannot be installed

### ISSUE THREAD

**Issue by joethei** [J-Barta/qb-reader-parser#1]
Hi @J-Barta 

We have noticed that the latest release of your plugin cannot be installed currently.

This is due to the following reason(s):
- No release found for version 1.9.2

We will remove this plugin from the community plugins directory if this issue is not fixed within 30 days.

- The Obsidian Team

**Comment by J-Barta** [comment]
Hello! It looks like the tag got created for version `1.9.2`, but it got created accidentally. Somehow, the GitHub Actions to generate the version release didn't run, so there was no `1.9.2` release. I've reuploaded the `1.9.2` tag, and the version has been properly created. I was able to successfully update on my device. Please let me know if the issue has been resolved on your side as well.
